### ISSUE TITLE
Obtain feedback from Molinillo and crystal-molinillo projects

### ISSUE THREAD

**Issue by baron1405** [cthing/molinillo4j#1]
I have created a Java port of the Molinillo dependency resolution algorithm. This is motivated by an investigation into dependency management algorithms and implementations for a potential Java build tool project. The port attempts to remain as true as possible to the original Ruby project. In addition, I have included the CocoaPods/Molinillo#153 and CocoaPods/Molinillo#158 PRs. All test cases from the Molinillo project are included and pass. I would greatly appreciate any feedback from @segiddins, @greysteil, @waj, and anyone else familiar with the algorithm. A big thank you to the [Molinillo](https://github.com/CocoaPods/Molinillo) and [crystal-molinillo](https://github.com/crystal-lang/crystal-molinillo) projects for their great work!

**Comment by greysteil** [comment]
Nice! I'll leave review to someone else - it's been a few years since I thought about dependency resolution now, but the ping put a 😄 on my face!
